"""
Django settings for genius_platform project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (  # nosec
    "django-insecure-$g*$jj+py9^bk=^u#%i@d8&pa*gxw8ouxj2grnfr0+4jn7tc^v"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS: list = ["localhost", "127.0.0.1", ".localhost", "testserver"]


# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "crm",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Unfold theme configuration
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Use WhiteNoise for serving compressed static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# WhiteNoise serves from STATIC_ROOT
STATIC_ROOT = BASE_DIR / "staticfiles"

ROOT_URLCONF = "genius_platform.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "genius_platform.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Stripe Configuration
STRIPE_PUBLISHABLE_KEY = ""  # nosec
STRIPE_SECRET_KEY = ""  # nosec
STRIPE_WEBHOOK_SECRET = ""  # nosec

# Funnel Configuration
FUNNEL_OFFER_EXPIRED_URL = "/offer-expired/"

# Unfold theme configuration with custom colors
UNFOLD = {
    "SITE_TITLE": "Genius CRM",
    "SITE_HEADER": "Cool Girl Rehab™",
    "COLORS": {
        "primary": {
            "50": "#faf6f1",  # Cream
            "100": "#f8e8e8",
            "200": "#f5d1d1",
            "300": "#f2baba",
            "400": "#efa3a3",
            "500": "#e93d3d",  # Orange
            "600": "#d21d13",  # Red
            "700": "#b3180f",
            "800": "#94140c",
            "900": "#771009",
            "950": "#222222",  # Dark
        },
    },
}

# Email Configuration
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# For real sending later, use:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-api-key'
# EMAIL_HOST_PASSWORD = 'your-password'

# Email Branding Settings
DEFAULT_FROM_EMAIL = "Cool Girl Rehab <hello@coolgirlrehab.com>"
EMAIL_LOGO_URL = "https://your-domain.com/logo.png"
EMAIL_COMPANY_ADDRESS = "123 Business St, City, State 12345"
EMAIL_SOCIAL_LINKS = '<a href="https://instagram.com">Instagram</a> | <a href="https://facebook.com">Facebook</a>'
EMAIL_UNSUBSCRIBE_URL = "/unsubscribe/"
EMAIL_PREFERENCES_URL = "/email-preferences/"
