# Generated by Django 4.2.29 on 2026-03-25 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_badge_emailsequence_emailsequencestep_funnel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="contact",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="pipeline_stage",
            field=models.CharField(
                choices=[
                    ("new_lead", "New Lead"),
                    ("contacted", "Contacted"),
                    ("qualified", "Qualified"),
                    ("proposal", "Proposal"),
                    ("negotiation", "Negotiation"),
                    ("closed_won", "Closed Won"),
                    ("closed_lost", "Closed Lost"),
                ],
                default="new_lead",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="products_purchased",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="contact",
            name="source",
            field=models.CharField(
                choices=[
                    ("lead_magnet_freebie_a", "Lead Magnet - Freebie A"),
                    ("lead_magnet_freebie_b", "Lead Magnet - Freebie B"),
                    ("webinar", "Webinar"),
                    ("referral", "Referral"),
                    ("organic", "Organic"),
                    ("instagram", "Instagram"),
                    ("paid_ad", "Paid Ad"),
                    ("manual", "Manual Entry"),
                ],
                default="organic",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.IntegerField(default=0)),
                ("include_in_chart", models.BooleanField(default=True)),
                ("include_in_distribution", models.BooleanField(default=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="crm.pipeline",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deal_value",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12
                    ),
                ),
                ("close_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.contact",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.pipeline",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.pipelinestage",
                    ),
                ),
            ],
        ),
    ]
