# Generated by Django 4.2.29 on 2026-03-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0003_pipeline_contact_address_contact_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funnel",
            name="tag",
            field=models.CharField(
                blank=True,
                help_text="Auto-tag applied to leads from this funnel",
                max_length=100,
            ),
        ),
    ]
