# Generated by Django 4.2.29 on 2026-03-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_contact_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='utm_content',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='utm_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='utm_term',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
