# Generated by Django 4.2.29 on 2026-03-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0006_contact_utm_campaign_contact_utm_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funnel",
            name="offer_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Offer expiration date/time for countdown timer",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="OrderBump",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "funnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_bumps",
                        to="crm.funnel",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.product",
                    ),
                ),
            ],
        ),
    ]
