# Generated by Django 4.2.29 on 2026-03-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0007_funnel_offer_end_date_orderbump"),
    ]

    operations = [
        migrations.AddField(
            model_name="funnelpage",
            name="template",
            field=models.CharField(
                blank=True, default="sales_template_1.html", max_length=100
            ),
        ),
    ]
