# Generated by Django 4.2.29 on 2026-03-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0008_funnelpage_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
